export const blogPosts = [
  {
    id: 1,
    slug: "basics-about-cryptocurrency",
    title: "The Basics about Cryptocurrency",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 2, 2021",
    image: "/images/blog-1.png", 
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here... This is the dynamic detail view."
  },
  {
    id: 2,
    slug: "security-in-defi",
    title: "Understanding Security in DeFi",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 5, 2021",
    image: "/images/blog-2.avif",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 3,
    slug: "future-of-ethereum",
    title: "The Future of Ethereum 2.0",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit. Scelerisque viverra donec diammeo.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 10, 2021",
    image: "/images/blog-3.avif",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
  id: 4,
  slug: "what-is-blockchain-technology",
  title: "What Is Blockchain Technology?",
  excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
  category: "PRODUCTS",
  author: "Alex Turner",
  date: "August 12, 2021",
  image: "/images/blog-5.jpeg",
  authorImage: "/images/asad.jpg",
  content: "Full article content goes here..."
  },
   {
    id: 5,
    slug: "basics-about-cryptocurrency",
    title: "The Basics about Cryptocurrency",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 2, 2021",
    image: "/images/blog-1.png", 
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here... This is the dynamic detail view."
  },
  {
    id: 6,
    slug: "how-smart-contracts-work",
    title: "How Smart Contracts Work",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 18, 2021",
    image: "/images/blog-6.jpg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 7,
    slug: "bitcoin-vs-ethereum",
    title: "Bitcoin vs Ethereum: Key Differences",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 20, 2021",
    image: "/images/blog-7.webp",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 8,
    slug: "what-is-defi",
    title: "What Is DeFi and Why It Matters",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 22, 2021",
    image: "/images/blog-8.jpg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 9,
    slug: "nfts-for-beginners",
    title: "NFTs Explained for Beginners",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 25, 2021",
    image: "/images/blog-9.jpg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 10,
    slug: "crypto-mining-basics",
    title: "Crypto Mining: The Basics",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 28, 2021",
    image: "/images/blog-10.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 11,
    slug: "proof-of-work-vs-proof-of-stake",
    title: "Proof of Work vs Proof of Stake",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "August 30, 2021",
    image: "/images/blog-11.avif",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 12,
    slug: "crypto-security-best-practices",
    title: "Crypto Security Best Practices",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 2, 2021",
    image: "/images/blog-12.webp",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 13,
    slug: "stablecoins-explained",
    title: "Stablecoins: Explained Simply",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 5, 2021",
    image: "/images/blog-13.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 14,
    slug: "layer-2-solutions",
    title: "Layer 2 Solutions in Blockchain",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 8, 2021",
    image: "/images/blog-13.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 15,
    slug: "web3-and-the-future-internet",
    title: "Web3 and the Future of the Internet",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 10, 2021",
    image: "/images/blog-13.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 16,
    slug: "dao-governance-models",
    title: "DAO Governance Models Explained",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 12, 2021",
    image: "/images/blog-13.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 17,
    slug: "crypto-regulations-worldwide",
    title: "Crypto Regulations Around the World",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 15, 2021",
    image: "/images/blog-13.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  },
  {
    id: 18,
    slug: "future-of-digital-assets",
    title: "The Future of Digital Assets",
    excerpt: "Lorem ipsum dolor sit ametero irseo, consectetur adipiscing elit.",
    category: "PRODUCTS",
    author: "Alex Turner",
    date: "September 18, 2021",
    image: "/images/blog-13.jpeg",
    authorImage: "/images/asad.jpg",
    content: "Full article content goes here..."
  }

];